# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = ""
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = []
license = "Unlicense"
description = ""
homepage = ""
repository = ""
keywords = []
categories = []
disciplines = []
compiler = ""
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
